CREATE TABLE categories(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    user_id int references users(id) not null
);

ALTER TABLE transactions ADD COLUMN category_id int references categories(id);